version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory:         "/"
    schedule:
      interval: "weekly"
    assignees:
      - "burgholzer"

  - package-ecosystem: "github-actions"
    directory:         "/"
    schedule:
      interval: "weekly"
    assignees:
      - "burgholzer"

  - package-ecosystem: "pip"
    directory:         "/docs"
    schedule:
      interval: "weekly"
    assignees:
      - "burgholzer"

  - package-ecosystem: "pip"
    directory:         "/test/python"
    schedule:
      interval: "weekly"
    assignees:
      - "burgholzer"
